export const LOGIN = "LOGIN";
export const LOADING_AUTH = "LOADING_AUTH";
export const LOADING_ACCOUNT = "LOADING_ACCOUNT";
export const FETCH_ACCOUNT_SUCESS = "FETCH_ACCOUNT_SUCESS";
export const FETCH_ACCOUNT_ERROR = "FETCH_ACCOUNT_ERROR";
export const LOGGOUT_ACCOUNT = "LOGGOUT_ACCOUNT";
export const LOGOUT = "LOGOUT";

export const LOADING_NOTES = "LOADING_NOTES";
export const CREATE_NOTE = "CREATE_NOTE";
export const SET_PAGE = "SET_PAGE";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const CHANGE_THEME = "CHANGE_THEME";
